package com.paascloud.provider.model.domain;

import java.util.Date;

public class MqMessageData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.message_key
     *
     * @mbg.generated
     */
    private String messageKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.message_topic
     *
     * @mbg.generated
     */
    private String messageTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.message_tag
     *
     * @mbg.generated
     */
    private String messageTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.message_type
     *
     * @mbg.generated
     */
    private Integer messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.delay_level
     *
     * @mbg.generated
     */
    private Integer delayLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.last_operator
     *
     * @mbg.generated
     */
    private String lastOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.last_operator_id
     *
     * @mbg.generated
     */
    private Long lastOperatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.yn
     *
     * @mbg.generated
     */
    private Integer yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_mq_message_data.message_body
     *
     * @mbg.generated
     */
    private String messageBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.id
     *
     * @return the value of pc_mq_message_data.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.id
     *
     * @param id the value for pc_mq_message_data.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.version
     *
     * @return the value of pc_mq_message_data.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.version
     *
     * @param version the value for pc_mq_message_data.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.message_key
     *
     * @return the value of pc_mq_message_data.message_key
     *
     * @mbg.generated
     */
    public String getMessageKey() {
        return messageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.message_key
     *
     * @param messageKey the value for pc_mq_message_data.message_key
     *
     * @mbg.generated
     */
    public void setMessageKey(String messageKey) {
        this.messageKey = messageKey == null ? null : messageKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.message_topic
     *
     * @return the value of pc_mq_message_data.message_topic
     *
     * @mbg.generated
     */
    public String getMessageTopic() {
        return messageTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.message_topic
     *
     * @param messageTopic the value for pc_mq_message_data.message_topic
     *
     * @mbg.generated
     */
    public void setMessageTopic(String messageTopic) {
        this.messageTopic = messageTopic == null ? null : messageTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.message_tag
     *
     * @return the value of pc_mq_message_data.message_tag
     *
     * @mbg.generated
     */
    public String getMessageTag() {
        return messageTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.message_tag
     *
     * @param messageTag the value for pc_mq_message_data.message_tag
     *
     * @mbg.generated
     */
    public void setMessageTag(String messageTag) {
        this.messageTag = messageTag == null ? null : messageTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.message_type
     *
     * @return the value of pc_mq_message_data.message_type
     *
     * @mbg.generated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.message_type
     *
     * @param messageType the value for pc_mq_message_data.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.delay_level
     *
     * @return the value of pc_mq_message_data.delay_level
     *
     * @mbg.generated
     */
    public Integer getDelayLevel() {
        return delayLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.delay_level
     *
     * @param delayLevel the value for pc_mq_message_data.delay_level
     *
     * @mbg.generated
     */
    public void setDelayLevel(Integer delayLevel) {
        this.delayLevel = delayLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.order_type
     *
     * @return the value of pc_mq_message_data.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.order_type
     *
     * @param orderType the value for pc_mq_message_data.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.status
     *
     * @return the value of pc_mq_message_data.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.status
     *
     * @param status the value for pc_mq_message_data.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.creator
     *
     * @return the value of pc_mq_message_data.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.creator
     *
     * @param creator the value for pc_mq_message_data.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.creator_id
     *
     * @return the value of pc_mq_message_data.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.creator_id
     *
     * @param creatorId the value for pc_mq_message_data.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.created_time
     *
     * @return the value of pc_mq_message_data.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.created_time
     *
     * @param createdTime the value for pc_mq_message_data.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.last_operator
     *
     * @return the value of pc_mq_message_data.last_operator
     *
     * @mbg.generated
     */
    public String getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.last_operator
     *
     * @param lastOperator the value for pc_mq_message_data.last_operator
     *
     * @mbg.generated
     */
    public void setLastOperator(String lastOperator) {
        this.lastOperator = lastOperator == null ? null : lastOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.last_operator_id
     *
     * @return the value of pc_mq_message_data.last_operator_id
     *
     * @mbg.generated
     */
    public Long getLastOperatorId() {
        return lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.last_operator_id
     *
     * @param lastOperatorId the value for pc_mq_message_data.last_operator_id
     *
     * @mbg.generated
     */
    public void setLastOperatorId(Long lastOperatorId) {
        this.lastOperatorId = lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.update_time
     *
     * @return the value of pc_mq_message_data.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.update_time
     *
     * @param updateTime the value for pc_mq_message_data.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.yn
     *
     * @return the value of pc_mq_message_data.yn
     *
     * @mbg.generated
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.yn
     *
     * @param yn the value for pc_mq_message_data.yn
     *
     * @mbg.generated
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_mq_message_data.message_body
     *
     * @return the value of pc_mq_message_data.message_body
     *
     * @mbg.generated
     */
    public String getMessageBody() {
        return messageBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_mq_message_data.message_body
     *
     * @param messageBody the value for pc_mq_message_data.message_body
     *
     * @mbg.generated
     */
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody == null ? null : messageBody.trim();
    }
}