package com.paascloud.provider.mapper;

import com.paascloud.provider.model.domain.UacRole;

public interface UacRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    int insert(UacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    int insertSelective(UacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    UacRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    int updateByPrimaryKeySelective(UacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_uac_role
     *
     * @mbg.generated Tue Jul 02 15:11:41 CST 2019
     */
    int updateByPrimaryKey(UacRole record);
}